// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5nKpoM7ym2-ZaKLMeAThe9vd38vlIm1c',
    appId: '1:830747880370:web:e00b326d92e29d994892ab',
    messagingSenderId: '830747880370',
    projectId: 'first-project-6ab3a',
    authDomain: 'first-project-6ab3a.firebaseapp.com',
    storageBucket: 'first-project-6ab3a.firebasestorage.app',
    measurementId: 'G-YKHDGD3NE0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWi3P_uj38TEWkLbW-PYFXy8j7jVyazFg',
    appId: '1:830747880370:android:baefeb9551e693084892ab',
    messagingSenderId: '830747880370',
    projectId: 'first-project-6ab3a',
    storageBucket: 'first-project-6ab3a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDH7s69PDGuGlvoOTzOBXXBHORG5bTA3x4',
    appId: '1:830747880370:ios:c6d9ae675fcfbd024892ab',
    messagingSenderId: '830747880370',
    projectId: 'first-project-6ab3a',
    storageBucket: 'first-project-6ab3a.firebasestorage.app',
    iosBundleId: 'com.example.myFirstApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDH7s69PDGuGlvoOTzOBXXBHORG5bTA3x4',
    appId: '1:830747880370:ios:c6d9ae675fcfbd024892ab',
    messagingSenderId: '830747880370',
    projectId: 'first-project-6ab3a',
    storageBucket: 'first-project-6ab3a.firebasestorage.app',
    iosBundleId: 'com.example.myFirstApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5nKpoM7ym2-ZaKLMeAThe9vd38vlIm1c',
    appId: '1:830747880370:web:5207a7dded29e6844892ab',
    messagingSenderId: '830747880370',
    projectId: 'first-project-6ab3a',
    authDomain: 'first-project-6ab3a.firebaseapp.com',
    storageBucket: 'first-project-6ab3a.firebasestorage.app',
    measurementId: 'G-EL31SJJ06E',
  );
}
